### ISSUE TITLE
Ssl mqtt call example

### ISSUE THREAD

**Issue by mirkoperillo** [batchcorp/plumber#281]
Hi,

I want to use plumber to test mqtts on a RabbitMQ instance. I have some issue to understand how to do it.
My attempts:

```
plumber write mqtt -d --address=ssl://user:password@localhost:8883 --topic=my-topic  --input pippo
FATA[0000] unable to complete command: unable to create new backend: unable to instantiate backend: unable to validate options: --tls-client-key-file cannot be blank if using ssl
```
But trying to add `--tls-client-key-file` I obtain

```
plumber write mqtt -d --address=ssl://user:password@localhost:8883 --topic=my-topic  --tls-client-key-file=client_key.pem --input pippo
FATA[0000] Unable to handle CLI input: unable to parse CLI options: unknown flag --tls-client-key-file
```

I'm using plumber v1.6.1.

Documentation doesn't contain example about this scenario. I have tried to look into the code but I miss something.
Ho can I use plumber against this scenario ?

**Comment by blinktag** [comment]
Hi @mirkoperillo, we should hopefully have a fix for this released shortly. I will update this issue as soon as we get that out!

**Comment by blinktag** [comment]
@mirkoperillo I have released a fix in https://github.com/batchcorp/plumber/releases/tag/v1.7.1

The correct TLS flags are actually `--tls-client-key`, `--tls-client-cert`, and `--tls-ca-cert`. The `-file` suffix was removed in a previous release, but the error messages never got updated. 

You won't need these flags now if you are just connecting over TLS instead of using mTLS auth. Let me know if you have any further trouble!

**Comment by mirkoperillo** [comment]
@blinktag I confirm that plumber version 1.7.1 worked as expected.

I'm available to improve the documentation about this scenario (so mqtt write on ssl). Can you tell me where is the best point in documentation to provide a couple of examples about this ?

For me the issue is resolved, I close it.
